Booking/Controllers/CartController.cs
using System;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using System.Transactions;
using Booking.Models;
using Booking.Models.DB;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Booking.Controllers
{
    //რაც შეეხება მომხმარებლის კალათს, მასთან მუშაობისას მომხმარებელი აუცილებლად უნდა იყოს დალოგინებული
    [Authorize]
    public class CartController : DbConnectionController
    {
        //კალათაში არსებული ბილეთების ნახვა
        public IActionResult Cart()
        {
            int userId = GetUserId();
            var userCart = db.UserCarts.FirstOrDefault(x => x.UserId == userId && x.IsClosed == null);
            if (userCart != null)
            {
                var cart = db.CartDetails.Where(x => x.CartId == userCart.Id).Select(x => new Cart()
                {
                    CartDetailsId = x.Id,
                    EventId = x.EventId,
                    EventName = x.Event.EventName,
                    RowNumber = x.Place.Row,
                    PlaceNumber = x.Place.PlaceNumber,
                    PlaceId = x.PlaceId,
                    Price = x.Event.TicketPrice
                });
                ViewBag.Amount = userCart.Amount;
                return View(cart);
            }
            else
            {
                return View();
            }
        }

        //კალათაში ახალი ბილეთის დამატება/დაჯავშნა (ბილეთების რაოდენობა იცვლება)
        public async Task<JsonResult> AddToCart(int eventId, int placeId)
        {
            var userid = GetUserId();
            var userCart = db.UserCarts.FirstOrDefault(x => x.UserId == userid && x.IsClosed == null);
            //თუ არსებობს გახსნილი კალათა, ჯავშანის დამატება ხდება მასში
            if (userCart != null)
            {
                var ticket = db.CartDetails.FirstOrDefault(x => x.EventId == eventId);
                db.CartDetails.Add(new CartDetails()
                {
                    CartId = userCart.Id,
                    EventId = eventId,
                    PlaceId = placeId,
                    AdditionDate = DateTime.Now
                });

                userCart.Amount += db.Events.FirstOrDefault(x => x.Id == eventId).TicketPrice;
                await db.SaveChangesAsync();
            }
            //სხვა შემთხვევაში ჯერ იქმნება ახალი კალათა და შედგომ ემატება ბილეთები
            else
            {
                var newCart = db.UserCarts.Add(new UserCarts()
                {
                    UserId = userid,
                    Amount = 0,
                    CreationDate = DateTime.Now
                });
                await db.SaveChangesAsync();

                db.CartDetails.Add(new CartDetails()
                {
                    CartId = db.UserCarts.FirstOrDefault(x => x.UserId == userid && x.IsClosed == null).Id,
                    EventId = eventId,
                    PlaceId = placeId,
                    AdditionDate = DateTime.Now
                });

                var cart = db.UserCarts.FirstOrDefault(x => x.UserId == userid && x.IsClosed == null);
                cart.Amount = db.Events.FirstOrDefault(x => x.Id == eventId).TicketPrice;
                await db.SaveChangesAsync();
            }
            await db.SaveChangesAsync();
            var place = db.EventPlaces.FirstOrDefault(x => x.Id == placeId);
            place.IsAvailable = false;
            await db.SaveChangesAsync();
            return Json("");
        }

        //კალათიდან ბილეთების წაშლა
        [HttpPost]
        public async Task<JsonResult> RemoveFromCart(int cartDetailsId, int placeId)
        {
            var userId = GetUserId();
            var cartEvent = db.CartDetails.FirstOrDefault(x => x.Id == cartDetailsId && x.PlaceId == placeId);
            var eventId = db.Events.FirstOrDefault(x => x.Id == cartEvent.EventId);
            var cart = db.UserCarts.FirstOrDefault(x => x.UserId == userId && x.IsClosed == null);

            cart.Amount -= eventId.TicketPrice;
            await db.SaveChangesAsync();

            db.CartDetails.Remove(cartEvent);
            await db.SaveChangesAsync();

            var returnedPlace = db.EventPlaces.FirstOrDefault(x => x.Id == placeId);
            returnedPlace.IsAvailable = true;
            await db.SaveChangesAsync();

            return Json("");
        }

        //მონაცემთა შემოწმების გვერდზე გადასვლა
        public IActionResult Purchase()
        {
            decimal sum = 0;
            int userId = db.Users.FirstOrDefault(x => x.Email == User.Identity.Name).Id;
            var cart = db.UserCarts.FirstOrDefault(x => x.UserId == userId && x.IsClosed == null);
            sum = cart.Amount;


            PurchaseClass pc = new PurchaseClass()
            {
                UserID = userId,
                FirstName = db.Users.FirstOrDefault(x => x.Id == userId).FirstName,
                LastName = db.Users.FirstOrDefault(x => x.Id == userId).LastName,
                TotalAmount = sum
            };
            return View(pc);
        }

        //ბილეთების შეძენა
        [HttpPost]
        public IActionResult Purchase(Sale sale)
        {
            using (TransactionScope transaction = new TransactionScope())
            {
                int userId = db.Users.FirstOrDefault(x => x.Email == User.Identity.Name).Id;
                var cartid = db.UserCarts.FirstOrDefault(x => x.UserId == userId && x.IsClosed == null).Id;
                var userCart = db.CartDetails.Where(x => x.CartId == db.UserCarts.FirstOrDefault(x => x.UserId == userId && x.IsClosed == null).Id);
                var lastDocNum = db.Sale.Select(x => x.DocNumber).ToList();

                if (lastDocNum.Count == 0)
                {
                    sale.DocNumber = 1;
                }
                else
                {
                    sale.DocNumber = lastDocNum.Last() + 1;
                }

                if (userCart != null)
                {
                    var cart = userCart.Select(x => new Cart()
                    {
                        CartDetailsId = x.Id,
                        EventId = x.EventId,
                        EventName = x.Event.EventName,
                        PlaceNumber = x.Place.PlaceNumber,
                        PlaceId = x.PlaceId,
                        Price = x.Event.TicketPrice
                    });
                    
                    //Sale ცხრილში მონაცემების გადატანა და უნიკალური Id-ის მინიჭება
                    foreach (var item in cart)
                    {
                    x1: string id = Guid.NewGuid().ToString("n").Substring(0, 32);
                        if (!db.Sale.Select(x => x.Id).Contains(id))
                        {
                            sale.Id = id;
                        }
                        else
                        {
                            goto x1;
                        }
                        sale.UserId = userId;
                        sale.EventId = item.EventId;
                        sale.CartId = cartid;
                        sale.PlaceId = item.PlaceId;
                        sale.Price = item.Price;
                        sale.Date = DateTime.Now;

                        db.Sale.Add(sale);
                        db.SaveChanges();
                    }
                }
                var userCartProduct = db.CartDetails.Where(x => x.CartId == cartid).Select(x => x.Id);

                //კალათის დეტალების გაწმენდა
                foreach (var item in userCartProduct)
                {
                    db.CartDetails.Remove(db.CartDetails.Find(item));
                }
                db.SaveChanges();

                //კალათის სტატუსის დახურვა
                var cartIsCompleted = db.UserCarts.FirstOrDefault(x => x.UserId == userId && x.IsClosed == null);
                cartIsCompleted.IsClosed = true;
                db.SaveChanges();
                transaction.Complete();
            }
            return RedirectToAction("Index", "Home");
        }

        //მომხმარებლის Id-ს მიღება
        public int GetUserId()
        {
            return db.Users.FirstOrDefault(x => x.Email == User.Identity.Name).Id;
        }
    }
}

Booking/Controllers/EventController.cs
using System;
using System.Linq;
using Booking.Models;
using Booking.Models.DB;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Booking.Controllers
{
    //ღონისძიებების და დეტალების დათვალიერება შეუძლიათ როგორც დალოგინებულ მომხმარებლებს, ასევე სტუმრებს
    [AllowAnonymous]
    public class EventController : DbConnectionController
    {
        public IActionResult AllEvents()
        {
            return View(db.Events.Where(x => x.EventDate >= DateTime.Today).OrderByDescending(x => x.EventDate).ToList());
        }

        public IActionResult Details(int id)
        {
            ViewBag.RowNumber = db.EventPlaces.Max(x=>x.Row);
            var eventInfo = db.Events.FirstOrDefault(x => x.Id == id);
            return View(new EventExtended()
            {
                Events = eventInfo,
                EventPlaces = db.EventPlaces.Where(x => x.EventId == eventInfo.Id).OrderBy(x=>x.Id)
            });
        }
    }
}

Booking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Booking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Event" asp-action="AllEvents">მთავარი გვერდი</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <div style="float:right">
                        <ul class="navbar-nav flex-grow-1">
                            @{
                                if (!User.Identity.IsAuthenticated)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignUp">რეგისტრაცია</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">შესვლა</a>
                                    </li>
                                }
                                else
                                {
                                    <li style="margin-top:8px">მოგესალმებით, @User.Identity.Name.</li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Cart">კალათა</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">გასვლა</a>
                                    </li>
                                }
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Booking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>